name: aymtools
description: "A commonly used toolkit in Flutter.
  Intended to make Flutter development more convenient.
  It includes a programmable some Listenable toolkits, data loaders, and some commonly used extensions."
version: 1.0.0-dev.7
homepage: https://github.com/aymtools/flutter_aymtools/

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependency_overrides:

dependencies:
  flutter:
    sdk: flutter

  async: any
  shared_preferences: any
  collection: any
  intl: any

  cancellable: ^2.0.1
  weak_collections: ^1.1.0
  anlifecycle: ^3.0.0
  isolate_pool_executor: ^1.2.0
  an_lifecycle_cancellable: ^1.0.0

#  ffx: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

