name: aymtools
description: "A commonly used toolkit in Flutter.
  Intended to make Flutter development more convenient.
  It includes a programmable some Listenable toolkits, data loaders, and some commonly used extensions."
version: 1.0.0-dev.9
homepage: https://github.com/aymtools/flutter_aymtools/

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependency_overrides:

dependencies:
  flutter:
    sdk: flutter

  async: any
  shared_preferences: any
  collection: any
  intl: any

  cancellable: any
  weak_collections: any
  anlifecycle: any
  an_lifecycle_cancellable: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

